# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Firebase-Swift-Demo' do
pod 'Firebase', '>= 2.5.1'
end

target 'Firebase-Swift-DemoTests' do
pod 'Firebase', '>= 2.5.1'
end

target 'Firebase-Swift-DemoUITests' do
pod 'Firebase', '>= 2.5.1'
end

